<package format="3">
  <name>so_arm_motion_interface</name>
  <version>0.0.0</version>
  <description>Pose target interface node that drives MoveIt for SO-ARM101</description>
  <maintainer email="jhjang@teamgrit.kr">teamgrit</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <exec_depend>moveit_servo</exec_depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf_transformations</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
