# Default initial positions for so101_new_calib's ros2_control fake system
# Order: Rotation, Pitch, Elbow, Wrist_Pitch, Wrist_Roll, Jaw

initial_positions:
  Rotation: 0.0
  Pitch: -1.35
  Elbow: 1.30
  Wrist_Pitch: 1.32
  Wrist_Roll: 1.52
  Jaw: 0.0
